### ISSUE TITLE
BTCTurk AuthenticationError hatası

### ISSUE THREAD

**Issue by ahmetcankaratas** [berke0bayraktar/btcturk-api-client#2]
Merhaba,

Private Endpointlerde özellikle bakiye sorgulamalarında zaman zaman Authentication hatası alıyorum,
Hata mesajı:

`{ statusCode: '401', statusText: 'Unauthorized' }`

Tam emin olamamakla birlikte hatanın timestampla ilgili olduğuna varsayıyorum ama emin değilim,

```
401 Unauthorized - Invalid Nonce
Nonce should not be different than the current timestamp we are giving a tolerance ±5 seconds.

Please check your server's timezone and timestamp output. It should be in milliseconds format and you need to declare your server's timezone to match UTC.
```
Benzer bir hata alıyormusun zaman zaman?  serverTime ile aradaki farklı eşitleyerek eklemeye çalıştım ancak çözüm olmadı, 

```
function calculateDrift() {
    const systemTime = getTime();
    return axios.request({
        method: "GET",
        url: "https://api.btcturk.com/api/v2/server/time"}
        ).then(response => {
        const transitTime = parseInt((getTime() - systemTime) / 2);
        drift = response.data.serverTime - (systemTime + transitTime);
        return drift
    }) 
};
```

**Comment by berke0bayraktar** [comment]
https://api.btcturk.com/api/v2/server/time şuradan server saatini sorgulayabiliyoruz. client ile server arasında en fazla 5 sn'lik zaman farkı tolere ediliyor. sende  bu fark daha fazla gibi bilgisayarın saatini server'a göre güncellemeyi denermisin

**Comment by berke0bayraktar** [comment]
doğrudan bilgisayarın saatini server time' a eşitlemeyi denedin mi?

**Comment by ahmetcankaratas** [comment]
doğru aslında server time ile ilgili olmayabilir, 

```
Dakikalık
/api/v1/users/balances | GET | 90
```
Örnek senaryo olarak:
dakikalık bakiye sorgulama limitleri dokümantasyonda 90 olarak belirlenmiş,
diyelimki 2 saniyede bir bakiye bilgilerini kontrol etmem gerekiyor sadece, burda 3-4 sorgulamada normal getiriyor sonrasında ise { statusCode: '401', statusText: 'Unauthorized' } hatası veriyor, 
neyle ilgili olabilir ? herşey aynı halbuki? axios/request paketleriyle ilgili olabilir mi? veya başka bir şey?

**Comment by berke0bayraktar** [comment]
bu şekilde hızlı işlem yapabilmek için bağlantının web socket ile kurulması gerekiyor sanırım. bana lazım olmadığı için kodu ilk yazarken çok üstünde durmamıştım.  eğer işini görecekse https://pypi.org/project/btcturk-api/ şurada python için çok daha düzgün yazılmış bi paket var

**Comment by ahmetcankaratas** [comment]
python paketleride aklımda, saolasın, bakalım belki diğer paketlerle çalışırken çözersem burayada eklerim

**Comment by bursar1983** [comment]
> python paketleride aklımda, saolasın, bakalım belki diğer paketlerle çalışırken çözersem burayada eklerim

selamlar durumu çözebildiniz mi aynı sorun bende de var

**Comment by meceware** [comment]
Cok test edemedim ama sanki sorunu asagidaki sekilde cozebilirsiniz:

```
function _getAuthHeaders() {
        const api_secret_b64_decoded = Buffer.from(API_SECRET, 'base64')
        const stamp = (new Date()).getTime()
        const data = `${API_KEY}${stamp}`
        const data_buffer = Buffer.from(data, 'utf8')
        const signature_buffer = crypto.createHmac('sha256', api_secret_b64_decoded)
        signature_buffer.update(data_buffer)
        const digest = signature_buffer.digest()
        const b64_encoded_signature_buffer = Buffer.from(digest.toString('base64'), 'utf8')
        const signature = b64_encoded_signature_buffer.toString('utf8')

        return {
            "X-PCK": API_KEY,
            "X-Stamp": stamp.toString(),
            "X-Signature": signature,
        }
    }
```

Burada hata anladigim kadariyla signature ile stamp'e verilen zaman farkliligindan kaynaklaniyor. Bu zamanlar ayni oldugunda sorun olusmuyor.

**Comment by berke0bayraktar** [comment]
> Cok test edemedim ama sanki sorunu asagidaki sekilde cozebilirsiniz:
> 
> ```
> function _getAuthHeaders() {
>         const api_secret_b64_decoded = Buffer.from(API_SECRET, 'base64')
>         const stamp = (new Date()).getTime()
>         const data = `${API_KEY}${stamp}`
>         const data_buffer = Buffer.from(data, 'utf8')
>         const signature_buffer = crypto.createHmac('sha256', api_secret_b64_decoded)
>         signature_buffer.update(data_buffer)
>         const digest = signature_buffer.digest()
>         const b64_encoded_signature_buffer = Buffer.from(digest.toString('base64'), 'utf8')
>         const signature = b64_encoded_signature_buffer.toString('utf8')
> 
>         return {
>             "X-PCK": API_KEY,
>             "X-Stamp": stamp.toString(),
>             "X-Signature": signature,
>         }
>     }
> ```
> 
> Burada hata anladigim kadariyla signature ile stamp'e verilen zaman farkliligindan kaynaklaniyor. Bu zamanlar ayni oldugunda sorun olusmuyor.

bunun icin pull request acabilir misin
